before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
#  - id: lib
#    env:
#      - CGO_ENABLED=1
#      - CC=zig cc
#    goos:
#      - linux
#    flags: -buildmode=c-shared
#    ldflags: -s -w
#    overrides:
#      - goos: linux
#        goarch: 386
#        env:
#          - CC=zig cc -target i386-linux
#      - goos: linux
#        goarch: amd64
#        goamd64: v1
#        env:
#          - CC=zig cc -target x86_64-linux
#      - goos: linux
#        goarch: arm64
#        env:
#          - CC=zig cc -target aarch64-linux
#      - goos: darwin
#        goarch: amd64
#        goamd64: v1
#        env:
#          - CC=zig cc -target x86_64-macos
#      - goos: darwin
#        goarch: arm64
#        env:
#          - CC=zig cc -target aarch64-macos
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
