before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: libfarmfa
    dir: libfarmfa
    binary: libfarmfa.so
    env:
      - CGO_ENABLED=1
    goos:
      - android
    goarch:
      - arm
      - arm64
    goarm:
      - 7
    flags: -buildmode=c-shared
    ldflags: -s -w
    overrides:
      - goos: android
        goarch: arm
        goarm: 7
        env:
          - CC=armv7a-linux-androideabi33-clang
      - goos: android
        goarch: arm64
        env:
          - CC=aarch64-linux-android33-clang
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
