= {product} Design Document
Giorgio Azzinnaro <giorgio@azzinna.ro>
v0.2, 2021-02-13
:toc:
:includedir: _include
:homepage: https://github.com/borgoat/farmfa
:product: farMFA

== Overview

{product} is a tool to improve the security of shared accounts protected by a TOTP <<RFC6238>>.
By splitting and distributing the secret among _n_ individuals -- via Shamir's Secret Sharing <<SSS>> --
the one-time password can only be generated by reconstructing the secret (with at least _t_ shares).
Because {product} oracle generates and returns only the current one-time password,
the users do not risk leaking the secret.

=== What problem does {product} solve?

{product} comes into play in enterprise environments, where access to certain accounts should be restricted.
Even with a proper Single Sign-On implementation, there are some exceptional cases where accounts are not nominal,
and need to be shared by multiple administrators.
Said accounts are also rather often particularly sensitive, and thus deserve multiple authentication factors.
While most teams already have a password manager, storing the TOTP secret in it defeats the purpose of MFA:
for increased security, it should be stored separately.

== Concept

{product} is composed of an oracle that reconstructs TOTP secrets, and generates the corresponding one-time password.
Users are conceptually divided between applicants (1 per session) and constituents (at least _t_ for each secret).
When an applicant needs access to a certain TOTP, they start a session, and ask players to join, by sharing their own Tocs.
Players (Toc holders) joining a session become constituents.
As soon as _t_ constituents have shared their Toc -- with {product} oracle, rather than the applicant directly --
the applicant may ask the oracle to reconstruct the TOTP secret, and generate a one-time password.
Because of this, the applicant will never receive the TOTP secret, hence they won't be able to generate
further one-time passwords, after their session ends.

== Design

=== TOTP secret splitting and Tocs generation

For any TOTP secret, the first step is for the dealer to split it, encrypt the resulting Tocs, and share them.
While the oracle MAY implement this functionality, it is RECOMMENDED this process is executed client-side.
This is the most vulnerable process as the dealer could accidentally leak the TOTP secret,
essentially voiding any further security measure taken afterwards.
At this initial step, the dealer decides how many players will receive a Toc (_n_),
and how many of them are required, to be able to reconstruct it (_t_). With stem:[t <= n].
Additionally, the dealer SHOULD define an encryption strategy for each player.

=== Starting a new session

When an applicant needs to access an account, and thus needs to generate the corresponding TOTP, they start a session.
A session is represented by an identifier (that of the group of Tocs).
Along with the identifier, the applicant is provided with a public key (Toc encryption key -- or _TEK_),
and a key encryption key (_KEK_).
With this information, the applicant can ask _n_ constituents to join the session.
More precisely, they share the public key, and the identifier.

=== Combining Tocs and generating one-time passwords

An applicant asks a constituent (a Toc holder) to join a session, and authorise them to generate a TOTP.
To identify the session, the applicant sends an identifier (that uniquely identifies the group of Tocs),
and a public key, that is unique to the current session.
The constituent who wants to authorise the applicant, will fetch their Toc based on the identifier,
encrypt it with the Toc encryption key, and send it to the oracle.
When _t_ constituents shared their Tocs with the oracle, the applicant may query the oracle,
with the session identifier along with the key encryption key.
With this information, the oracle can decrypt the Toc encryption key, and with that decrypt all Tocs.
With all Tocs, the oracle may now generate 1 TOTP and share it back to the applicant.

=== Flows
==== Splitting the TOTP secret (_Deal_)
The first flow happens when "enabling" the TOTP authentication.
A dealer is splitting a TOTP secret, encrypting the resulting Tocs, and sharing them with players.
In this flow, the oracle is not required, although it MAY implement this capability.

[plantuml]
....
actor     dealer as d
actor     "player 1" as p1
actor     "player 2" as p2

d -> d:   Split(Secret, PublicKeys[n]) = [{Toc<sub>1</sub>}<sub>K1</sub> .. {Toc<sub>n</sub>}<sub>Kn</sub>]

note left
The TOTP //secret// is split
in **n** //Tocs//, according to
the number of public keys.
end note

d -> p1:  Send {Toc<sub>1</sub>}<sub>K1</sub>
d -> p2:  Send {Toc<sub>2</sub>}<sub>K2</sub>

note left
Each player receives
a //Toc// encrypted
with their public key.
end note

....


==== Generating a TOTP (_Session_)
This flows is used whenever an applicant requires to authenticate to a service, and thus to generate a TOTP.

[plantuml]
....
actor     applicant as a
boundary  oracle as o
actor     "constituent 1" as c1
actor     "constituent 2" as c2

a -> o:   CreateSession(Toc<sub>1</sub>)
return    SessionKeypair(KEK, TEK, GroupID)

note right
SessionKeypair is composed of:
* key encryption key (KEK)
* Toc encryption public key (TEK)
* Toc Group identifier (GroupID)
end note

a  -> c1:  Share (TEK, GroupID)
a  -> c2:  Share (TEK, GroupID)
c1 -> o:   Send {Toc<sub>2</sub>}<sub>TEK</sub>
c2 -> o:   Send {Toc<sub>3</sub>}<sub>TEK</sub>

a ->  o:   GenerateTOTP (KEK)
o --> o:   decrypt TEK with KEK,\nthen each Toc with TEK
o --> o:   join decrypted Tocs\nand generate TOTP
o --> a:   TOTP
....


include::{includedir}/bibliography.adoc[]
include::{includedir}/glossary.adoc[]
