= {product} Design Document
Giorgio Azzinnaro <giorgio@azzinna.ro>
v0.1, 2020-11-07
:toc:
:homepage: https://github.com/giorgioazzinnaro/farmfa
:product: farMFA

== Overview

{product} is a tool to improve the security of shared accounts protected by a TOTP <<RFC6238>>.
By splitting and distributing the secret among _n_ individuals -- via Shamir's Secret Sharing <<SSS>> --
the one-time password can only be generated by reconstructing the secret (with at least _t_ shares).
Because {product} server generates and returns only the current one-time password,
the users do not risk leaking the secret.

== What problem does {product} solve?

{product} comes into play in enterprise environments, where access to certain accounts should be restricted.
Even with a proper Single Sign-On implementation, there are some exceptional cases where accounts are not nominal,
and need to be shared by multiple administrators.
Said accounts are also rather often particularly sensitive, and thus deserve multiple authentication factors.
While most teams already have a password manager, storing the TOTP secret in it defeats the purpose of MFA:
for increased security, it should be stored separately.

== Concept

{product} is composed of a server that reconstructs TOTP secrets, and generates the corresponding one-time password.
The users are conceptually divided between dealers (1 per session) and players (at least _t_ for each secret).

== Design

=== Flows
[plantuml]
....
actor     Dealer as d
boundary  Server as s
actor     "Player 1" as p1
actor     "Player 2" as p2

d -> p1:  share
d -> p2:  share

...

d -> s:   start session
return    return keypair

d  -> p1:  public key
d  -> p2:  public key
p1 -> s:   share encrypted with public key
p2 -> s:   share encrypted with public key

d  -> s:   generate TOTP (privat key)
return     return one-time password
....

[bibliography]
== References

- [[[RFC6238]]] M'Raihi, D., Machani, S., Pei, M., and J. Rydell, "TOTP: Time-Based One-Time Password Algorithm",
                RFC 6238, DOI 10.17487/RFC6238, May 2011, <https://www.rfc-editor.org/info/rfc6238>.
- [[[SSS,2]]] Adi Shamir. 1979. How to share a secret. Commun. ACM 22, 11 (Nov. 1979), 612–613.
            DOI:https://doi.org/10.1145/359168.359176

== Glossary

dealer::

player::

secret::

Toc::

TOTP::  As defined in <<RFC6238>>:
        "an extension of the One-Time Password (OTP) algorithm [...] to support the time-based moving factor".
        Used by many applications as a second authentication factor.
