// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// DecryptedShare defines model for DecryptedShare.
type DecryptedShare struct {

	// The share from the current user
	Share string `json:"share"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// NewSession defines model for NewSession.
type NewSession struct {

	// A first share owned by the dealer
	FirstShare string `json:"first_share"`

	// Seconds until the TOTP generation endpoint expires, starting from the first token generated.
	Ttl *int `json:"ttl,omitempty"`
}

// PrivateSession defines model for PrivateSession.
type PrivateSession struct {
	// Embedded struct due to allOf(#/components/schemas/Session)
	Session
	// Embedded struct due to allOf(#/components/schemas/SessionCredentials)
	SessionCredentials
}

// Session defines model for Session.
type Session struct {

	// True when the session either expired or the token was already retrieved by the dealer
	Closed *bool `json:"closed,omitempty"`

	// When the sessions will close down and no longer accept shares
	ClosesAt *time.Time `json:"closes_at,omitempty"`

	// True when enough shares have been provided
	Complete *bool `json:"complete,omitempty"`

	// The time when the session started
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// The public identifier of a session
	Id *string `json:"id,omitempty"`

	// The prefix to identify shares from different secrets
	ShareGroup *string `json:"share_group,omitempty"`

	// The total number of shares
	Shares *int `json:"shares,omitempty"`

	// The minimum number of shares required
	Threshold *int `json:"threshold,omitempty"`

	// Seconds until the TOTP generation endpoint expires, starting from the first token generated.
	Ttl *int `json:"ttl,omitempty"`
}

// SessionCredentials defines model for SessionCredentials.
type SessionCredentials struct {

	// The password to retrieve a TOTP from a session
	Private *string `json:"private,omitempty"`
}

// TOTPCode defines model for TOTPCode.
type TOTPCode struct {

	// The time when this endpoint will expire and cannot be called again
	EndpointExpiresAt *time.Time `json:"endpoint_expires_at,omitempty"`

	// The current TOTP
	Totp *string `json:"totp,omitempty"`

	// The time when the current TOTP will expire
	TotpExpiresAt *time.Time `json:"totp_expires_at,omitempty"`
}

// TOTPSecret defines model for TOTPSecret.
type TOTPSecret struct {

	// The keys to encrypt the shares, its length must be equal to `shares`
	EncryptionKeys *[]struct {
		From *string `json:"from,omitempty"`

		// Address to retrieve the public key
		Search *string `json:"search,omitempty"`
	} `json:"encryption_keys,omitempty"`

	// The number of shares to create
	Shares int `json:"shares"`

	// The minimum number of shares required to generate the TOTP
	Threshold int `json:"threshold"`

	// The secret key to generate the TOTP, either as a path or just the Base32 secret
	TotpSecretKey string `json:"totp_secret_key"`
}

// TOTPShares defines model for TOTPShares.
type TOTPShares struct {
	Shares []UserShare `json:"shares"`
}

// UserShare defines model for UserShare.
type UserShare struct {

	// The possibly encrypted share for this user
	Share string `json:"share"`

	// The user this share belongs to
	User *string `json:"user,omitempty"`
}

// DefaultError defines model for DefaultError.
type DefaultError Error

// CreateSessionJSONBody defines parameters for CreateSession.
type CreateSessionJSONBody NewSession

// PostShareJSONBody defines parameters for PostShare.
type PostShareJSONBody DecryptedShare

// GenerateTotpJSONBody defines parameters for GenerateTotp.
type GenerateTotpJSONBody SessionCredentials

// CreateSharesJSONBody defines parameters for CreateShares.
type CreateSharesJSONBody TOTPSecret

// CreateSessionRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody CreateSessionJSONBody

// PostShareRequestBody defines body for PostShare for application/json ContentType.
type PostShareJSONRequestBody PostShareJSONBody

// GenerateTotpRequestBody defines body for GenerateTotp for application/json ContentType.
type GenerateTotpJSONRequestBody GenerateTotpJSONBody

// CreateSharesRequestBody defines body for CreateShares for application/json ContentType.
type CreateSharesJSONRequestBody CreateSharesJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A callback for modifying requests which are generated before sending over
	// the network.
	RequestEditor RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = http.DefaultClient
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditor = fn
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateSession request  with any body
	CreateSessionWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	CreateSession(ctx context.Context, body CreateSessionJSONRequestBody) (*http.Response, error)

	// GetSession request
	GetSession(ctx context.Context, id string) (*http.Response, error)

	// PostShare request  with any body
	PostShareWithBody(ctx context.Context, id string, contentType string, body io.Reader) (*http.Response, error)

	PostShare(ctx context.Context, id string, body PostShareJSONRequestBody) (*http.Response, error)

	// GenerateTotp request  with any body
	GenerateTotpWithBody(ctx context.Context, id string, contentType string, body io.Reader) (*http.Response, error)

	GenerateTotp(ctx context.Context, id string, body GenerateTotpJSONRequestBody) (*http.Response, error)

	// CreateShares request  with any body
	CreateSharesWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	CreateShares(ctx context.Context, body CreateSharesJSONRequestBody) (*http.Response, error)
}

func (c *Client) CreateSessionWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewCreateSessionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSession(ctx context.Context, body CreateSessionJSONRequestBody) (*http.Response, error) {
	req, err := NewCreateSessionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) GetSession(ctx context.Context, id string) (*http.Response, error) {
	req, err := NewGetSessionRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) PostShareWithBody(ctx context.Context, id string, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewPostShareRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) PostShare(ctx context.Context, id string, body PostShareJSONRequestBody) (*http.Response, error) {
	req, err := NewPostShareRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateTotpWithBody(ctx context.Context, id string, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewGenerateTotpRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateTotp(ctx context.Context, id string, body GenerateTotpJSONRequestBody) (*http.Response, error) {
	req, err := NewGenerateTotpRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSharesWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewCreateSharesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) CreateShares(ctx context.Context, body CreateSharesJSONRequestBody) (*http.Response, error) {
	req, err := NewCreateSharesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

// NewCreateSessionRequest calls the generic CreateSession builder with application/json body
func NewCreateSessionRequest(server string, body CreateSessionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSessionRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateSessionRequestWithBody generates requests for CreateSession with any type of body
func NewCreateSessionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/sessions")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// NewGetSessionRequest generates requests for GetSession
func NewGetSessionRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParam("simple", false, "id", id)
	if err != nil {
		return nil, err
	}

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/sessions/%s", pathParam0)
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryUrl.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostShareRequest calls the generic PostShare builder with application/json body
func NewPostShareRequest(server string, id string, body PostShareJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostShareRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostShareRequestWithBody generates requests for PostShare with any type of body
func NewPostShareRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParam("simple", false, "id", id)
	if err != nil {
		return nil, err
	}

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/sessions/%s/shares", pathParam0)
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// NewGenerateTotpRequest calls the generic GenerateTotp builder with application/json body
func NewGenerateTotpRequest(server string, id string, body GenerateTotpJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateTotpRequestWithBody(server, id, "application/json", bodyReader)
}

// NewGenerateTotpRequestWithBody generates requests for GenerateTotp with any type of body
func NewGenerateTotpRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParam("simple", false, "id", id)
	if err != nil {
		return nil, err
	}

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/sessions/%s/totp", pathParam0)
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// NewCreateSharesRequest calls the generic CreateShares builder with application/json body
func NewCreateSharesRequest(server string, body CreateSharesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSharesRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateSharesRequestWithBody generates requests for CreateShares with any type of body
func NewCreateSharesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/shares")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateSession request  with any body
	CreateSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*CreateSessionResponse, error)

	CreateSessionWithResponse(ctx context.Context, body CreateSessionJSONRequestBody) (*CreateSessionResponse, error)

	// GetSession request
	GetSessionWithResponse(ctx context.Context, id string) (*GetSessionResponse, error)

	// PostShare request  with any body
	PostShareWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader) (*PostShareResponse, error)

	PostShareWithResponse(ctx context.Context, id string, body PostShareJSONRequestBody) (*PostShareResponse, error)

	// GenerateTotp request  with any body
	GenerateTotpWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader) (*GenerateTotpResponse, error)

	GenerateTotpWithResponse(ctx context.Context, id string, body GenerateTotpJSONRequestBody) (*GenerateTotpResponse, error)

	// CreateShares request  with any body
	CreateSharesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*CreateSharesResponse, error)

	CreateSharesWithResponse(ctx context.Context, body CreateSharesJSONRequestBody) (*CreateSharesResponse, error)
}

type CreateSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrivateSession
}

// Status returns HTTPResponse.Status
func (r CreateSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Session
}

// Status returns HTTPResponse.Status
func (r GetSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostShareResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostShareResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostShareResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateTotpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TOTPCode
}

// Status returns HTTPResponse.Status
func (r GenerateTotpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateTotpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateSharesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TOTPShares
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateSharesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSharesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateSessionWithBodyWithResponse request with arbitrary body returning *CreateSessionResponse
func (c *ClientWithResponses) CreateSessionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*CreateSessionResponse, error) {
	rsp, err := c.CreateSessionWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseCreateSessionResponse(rsp)
}

func (c *ClientWithResponses) CreateSessionWithResponse(ctx context.Context, body CreateSessionJSONRequestBody) (*CreateSessionResponse, error) {
	rsp, err := c.CreateSession(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseCreateSessionResponse(rsp)
}

// GetSessionWithResponse request returning *GetSessionResponse
func (c *ClientWithResponses) GetSessionWithResponse(ctx context.Context, id string) (*GetSessionResponse, error) {
	rsp, err := c.GetSession(ctx, id)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionResponse(rsp)
}

// PostShareWithBodyWithResponse request with arbitrary body returning *PostShareResponse
func (c *ClientWithResponses) PostShareWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader) (*PostShareResponse, error) {
	rsp, err := c.PostShareWithBody(ctx, id, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParsePostShareResponse(rsp)
}

func (c *ClientWithResponses) PostShareWithResponse(ctx context.Context, id string, body PostShareJSONRequestBody) (*PostShareResponse, error) {
	rsp, err := c.PostShare(ctx, id, body)
	if err != nil {
		return nil, err
	}
	return ParsePostShareResponse(rsp)
}

// GenerateTotpWithBodyWithResponse request with arbitrary body returning *GenerateTotpResponse
func (c *ClientWithResponses) GenerateTotpWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader) (*GenerateTotpResponse, error) {
	rsp, err := c.GenerateTotpWithBody(ctx, id, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseGenerateTotpResponse(rsp)
}

func (c *ClientWithResponses) GenerateTotpWithResponse(ctx context.Context, id string, body GenerateTotpJSONRequestBody) (*GenerateTotpResponse, error) {
	rsp, err := c.GenerateTotp(ctx, id, body)
	if err != nil {
		return nil, err
	}
	return ParseGenerateTotpResponse(rsp)
}

// CreateSharesWithBodyWithResponse request with arbitrary body returning *CreateSharesResponse
func (c *ClientWithResponses) CreateSharesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*CreateSharesResponse, error) {
	rsp, err := c.CreateSharesWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseCreateSharesResponse(rsp)
}

func (c *ClientWithResponses) CreateSharesWithResponse(ctx context.Context, body CreateSharesJSONRequestBody) (*CreateSharesResponse, error) {
	rsp, err := c.CreateShares(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseCreateSharesResponse(rsp)
}

// ParseCreateSessionResponse parses an HTTP response from a CreateSessionWithResponse call
func ParseCreateSessionResponse(rsp *http.Response) (*CreateSessionResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &CreateSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrivateSession
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSessionResponse parses an HTTP response from a GetSessionWithResponse call
func ParseGetSessionResponse(rsp *http.Response) (*GetSessionResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GetSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Session
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostShareResponse parses an HTTP response from a PostShareWithResponse call
func ParsePostShareResponse(rsp *http.Response) (*PostShareResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PostShareResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	}

	return response, nil
}

// ParseGenerateTotpResponse parses an HTTP response from a GenerateTotpWithResponse call
func ParseGenerateTotpResponse(rsp *http.Response) (*GenerateTotpResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &GenerateTotpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TOTPCode
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateSharesResponse parses an HTTP response from a CreateSharesWithResponse call
func ParseCreateSharesResponse(rsp *http.Response) (*CreateSharesResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &CreateSharesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TOTPShares
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start a new authentication session
	// (POST /sessions)
	CreateSession(ctx echo.Context) error

	// (GET /sessions/{id})
	GetSession(ctx echo.Context, id string) error

	// (POST /sessions/{id}/shares)
	PostShare(ctx echo.Context, id string) error

	// (POST /sessions/{id}/totp)
	GenerateTotp(ctx echo.Context, id string) error
	// Split a TOTP secret key
	// (POST /shares)
	CreateShares(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// GetSession converts echo context to params.
func (w *ServerInterfaceWrapper) GetSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSession(ctx, id)
	return err
}

// PostShare converts echo context to params.
func (w *ServerInterfaceWrapper) PostShare(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostShare(ctx, id)
	return err
}

// GenerateTotp converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateTotp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GenerateTotp(ctx, id)
	return err
}

// CreateShares converts echo context to params.
func (w *ServerInterfaceWrapper) CreateShares(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateShares(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST("/sessions", wrapper.CreateSession)
	router.GET("/sessions/:id", wrapper.GetSession)
	router.POST("/sessions/:id/shares", wrapper.PostShare)
	router.POST("/sessions/:id/totp", wrapper.GenerateTotp)
	router.POST("/shares", wrapper.CreateShares)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZXVPjOBb9KyrtPHqSQEhD52lDmp5iP6a7it7ahxmWubGubYEsGUmOCV3571uS7MRJ",
	"bDp00VPzFizp6OjcD90rvtJY5YWSKK2h069UoymUNOj/+IAJlMJeaa20+ztW0qK07icUheAxWK7k8N4o",
	"6b6ZOMMc3K+fNCZ0Sv823IIPw6gZBrT1eh1RhibWvHAgdEpLiU8FxhYZwXpOVGPWbGK9Kiyymww0ui+F",
	"VgVqywNb03zehf2SIfFDJNEqJzZDEpdao7SkNKhpRO2qQDqlxmouU7+rxseSa2R0+lsNe7uZphb3GFu6",
	"juhGl10esWKeBsoydwDXcgmCsy+fvny+wVijbYE1e0Y0R2Mg9Qtf5uPht/O7iP2K1Q0aw4NZdtklXBt7",
	"16PVjPjhWi9VSWRksfKaMQTRpVZErRUByTsLnb4b7Vv2BmMlmSGltFx4NCcGSVGi9i5EULJCcWkJPhVc",
	"o4mIsaAtl+nWaoGaVQ8om6XIBk4KeOK50/ri3dloFNGcy/C3Y1LT5dJiivpAzbYcXVJ+1nwJFltyghCf",
	"Ejr97WUvbxaso6PmzTUylJaDMHTdxaPXnrFQxh3lwO11iaTKUHrtTFhOkNsMda0yI0r70aBpBYaA0Ahs",
	"RTRazXHZb/6FUgLBnS8wMHdgD0n8d29/QyouBPErCFOVJCAZkYoIJVPUBOIYi9r9DI1oonTucCkDiz9b",
	"nmOXAzpZBVp8SQSUqkyzGplksESyQJSk0GrJGbLuk2l0PtZ5NJdWHKFDjb3nesTj6HPWjV6UC8Fjwr1j",
	"JBw1UQmBZpsuJH+6u1SrsuiB1JjwJ2JVg7pqFPFRxniSoM+Mxicq07uJ6RFEWRBElvkisN0YchOSp4cR",
	"GVGbaTSZEj1C1IsPcMkmkL+5QZOi/sJZqS/k26nhIPqLkJ56rA3GVEozZ+8moAmEU3r+LzhTFyG3cF5f",
	"brs0GqHuaqGOihhutgL7tBAW+5QQg5TKkgWSGIRARiAFLo8OKatsTwQ0V787C41oAdaidoP/+/139vXd",
	"+qc+uFcdbXef9umOPEKf/HUB0WEAXxtxJe8ecNUTnW7E+UI9OSQtH0kR4dYQgTK1GclL45XHxxKEm/9H",
	"mPQHjSg+gcu1/vpzLkSntEgLGtEHLhmdUo25su48BkHHGZ3Sk8uLyYfLs/HVxen4fPJhfnl1OXk/mV+c",
	"jE4m7z/Oz8ZX5x/PZrMTf1PWkA+4WoDBAVcvIadc6ZQreH7mUoJWAaER19VGkUMKv08exfj5PLtfTc6K",
	"apytqmoCq1WSnj8/psv4vBrfn6KoLp5zfX/6kE5MIt/DYx5DfNE6nVAxCOoKiJgX3FfCDYu/1zQGjsdt",
	"RLnFvCNewwG3tWEt3s55cWUGRbnorBKbwx8UboxpNGYn0u32DnEyHOVj9QfQGlb7yb4u7yZRh2sdpGar",
	"SLg9204zeeVFUO84jr7nUnAUmoS8ye5tNuNvsnFhH27CO+9Ina2FH3cKd24YNSWXK65IATZzRde9CzE3",
	"5RIMjk9rkG+2IvuENvZpK3fblzo2puxom/yvjc++VLD+x6AODdiBu3Q1TqaTzxbkNV1coYzhC7FqEhiy",
	"prHzdSw3PQ1dRP33Tkw3EtYGqAW6UtT573c3hm4el4lqOmaIfcLGHLjoThgRlZA7iF/CGJltclpES+1W",
	"ZdYWZjoc1qsH7XSzHx4zSWafr5075iAhxeYSsnX9y1rlneAxSuMFrznMCogzJKeD0cHmVVUNwA8PlE6H",
	"9Voz/Nf1/OrXm6ufTwejQWZz4V2DWxdkNAH9748zGtEl6tDB0NHgZDByc1SBEgpOp3Q8GPn9XIB4Nxg2",
	"HYP3EGW8hM5PfGV27bLx3OeXm00F42yDxl4qtnqzx4pWJ71eBwdovY+cjkZvttNeo9nxPvLpn+FFpMxz",
	"0O5au3HFKAEisSJQ2sxViWHvdl0HqfHeWn+5dRgbdYdfOVs7ail2KPwL2q28BWjI0aI2/vbf5Xb9wWfg",
	"ugNq3ULUxYKrEsBmWz/njLZjyeoSo5ZO+3F3+wN1/7bgRyg43CbRxld3of6huKwtFfKMVQQkwSdufDux",
	"tdeuBT4rY0OifJUBXEKsMh5nfh/GtqXe29nj7YNt74GvP+AOzRTRs66hS2CkZnq0KZveoduQc/900W73",
	"XbvSVWfsh1KY8cWhf78tuzb6y9qz623rxybRTYf66mg+iN/Ou6aptn6EWq327k9QqT5Kj07Rtvjuhtpw",
	"G+78j2DvfioEt82Dw7ZObl9KdYnoaRjUyyYgduuOBHSewKCu3AexyofLExBFBqFtDLOHdH27/n8AAAD/",
	"/24gLALQGAAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
